# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TbzkWGb_Kjcev4PNst946eJUm0e3tgxx
"""

import os

inventario = {
    "1": {"nombre": "Martillo", "precio": 15000, "stock": 10},
    "2": {"nombre": "Destornillador", "precio": 25000, "stock": 20},
    "3": {"nombre": "Cegueta", "precio": 12000, "stock": 30},
    "4": {"nombre": "Llave inglesa", "precio": 12000, "stock": 3},
    "5": {"nombre": "prenza", "precio": 12000, "stock": 12},
    "6": {"nombre": "tuerca", "precio": 8000, "stock": 0},
    "7": {"nombre": "llave", "precio": 6000, "stock": 1},


}

factura_actual = []

def limpiar_pantalla():
    os.system('cls' if os.name == 'nt' else 'clear')

def mostrar_inventario():
    print("\n*** INVENTARIO ***")
    print(f"{'ID':<6}{'NOMBRE':<20}{'PRECIO':<10}{'STOCK':<8}")
    print("_" * 50)

    for id_Prod, datos in inventario.items():
        print(f"{id_Prod:<6}{datos['nombre']:<20}{datos['precio']:<10.2f}{datos['stock']:<8}")

def buscar_productos():
    termino = input("Buscar producto: ").lower()
    encontrado = False

    for id_Prod, datos in inventario.items():
        if termino in datos['nombre'].lower():
            print(f"{id_Prod} - {datos['nombre']} - Stock: {datos['stock']}")
            encontrado = True

    if not encontrado:
        print("No encontrado.")

def agregar_producto():
    id_Prod = input("Nuevo ID: ")

    if id_Prod in inventario:
        print("Ya existe.")
        return

    nombre = input("Nombre: ")
    precio = float(input("Precio: "))
    stock = int(input("Stock: "))

    inventario[id_Prod] = {
        "nombre": nombre,
        "precio": precio,
        "stock": stock
    }

def modificar():
    id_Prod = input("ID a modificar: ")

    if id_Prod in inventario:
        prod = inventario[id_Prod]

        print("1. Aumentar stock")
        print("2. Cambiar precio")

        opcion = input("Opción: ")

        if opcion == "1":
            cantidad = int(input("Cantidad: "))
            prod['stock'] += cantidad

        elif opcion == "2":
            nuevo_precio = float(input("Nuevo precio: "))
            prod['precio'] = nuevo_precio

    else:
        print("No existe.")

def eliminar_productos():
    id_Prod = input("ID a eliminar: ")

    if id_Prod in inventario:
        inventario.pop(id_Prod)
        print("Eliminado.")
    else:
        print("No encontrado.")

def vender_producto():
    mostrar_inventario()
    id_Prod = input("ID producto: ")

    if id_Prod in inventario:
        prod = inventario[id_Prod]

        cantidad = int(input("Cantidad: "))

        if cantidad <= prod['stock']:
            subtotal = cantidad * prod['precio']
            prod['stock'] -= cantidad

            factura_actual.append({
                "nombre": prod['nombre'],
                "cantidad": cantidad,
                "precio": prod['precio'],
                "subtotal": subtotal
            })

            print(f"Agregado: ${subtotal:.2f}")
        else:
            print("Stock insuficiente.")
    else:
        print("No existe.")

def generar_factura():
    print("\n" + "=" * 40)
    print("FACTURA")

    total = 0

    for item in factura_actual:
        print(f"{item['nombre']} x{item['cantidad']} = ${item['subtotal']:.2f}")
        total += item['subtotal']

    print("=" * 40)
    print(f"TOTAL: ${total:.2f}")

    factura_actual.clear()

def main():
    while True:
        print("\n1. Inventario")
        print("2. Buscar")
        print("3. Vender")
        print("4. Factura")
        print("5. Agregar")
        print("6. Modificar")
        print("7. Eliminar")
        print("8. Salir")

        opcion = input("Opción: ")

        match opcion:
            case "1": mostrar_inventario()
            case "2": buscar_productos()
            case "3": vender_producto()
            case "4": generar_factura()
            case "5": agregar_producto()
            case "6": modificar()
            case "7": eliminar_productos()
            case "8": break
            case _: print("Inválido")

if __name__ == "__main__":
    main()

import os

# Catálogo de enfermedades psicológicas
inventario = {
    "1": {"nombre": "Esquizofrenia", "nivel": "grave","prioridad": "alta", "casos": 10},
    "2": {"nombre": "Trastornos de ansiedad", "nivel": "moderado", "prioridad": "alta", "casos": 20},
    "3": {"nombre": "Trastornos del estado de ánimo", "nivel": "moderado", "prioridad": "alta","casos": 30},
    "4": {"nombre": "Trastornos psicóticos", "nivel": "grave", "prioridad": "alta","casos": 12},
    "5": {"nombre": "Trastornos de la conducta alimentaria", "nivel": "moderado", "prioridad": "alta","casos": 5},
    "6": {"nombre": "Trastornos del neurodesarrollo", "nivel": "leve", "prioridad": "alta","casos": 8},
    "7": {"nombre": "Trastorno de estrés postraumático", "nivel": "grave", "prioridad": "alta", "casos": 6},
}

casos_actuales = []

def limpiar_pantalla():
    os.system('cls' if os.name == 'nt' else 'clear')

def mostrar_Enfermedades_psicotratables():
    print("\n*** Categorización psicotratables ***")
    print(f"{'ID':<6}{'nivel':<20}{'nivel':<10}{'casos':<8}")
    print("_" * 50)

    for id_Prod, datos in mostrar_Enfermedades_psicotratables.items():
        print(f"{id_Prod:<6} {datos['nombre']:<20} {datos['nivel']:<10.2f} {datos['prioridad']:<10} {datos['casos']:<8}")

def buscar_por_prioridad():
    p = input("Ingrese prioridad (alta/media/baja): ").lower()

    for id_e, datos in inventario.items():
        if datos['prioridad'] == p:
            print(f"{id_e} - {datos['nombre']} ({datos['nivel']})")

def agregar_asignar_por_prioridad(nivel):
    id_Prod = input("Nuevo ID: ")

    if id_Prod in mostrar_Enfermedades_psicotratables:
        print("Ya existe.")
        return
    if nivel == "grave":
        return "alta"
    elif nivel == "moderado":
        return "media"
    else:
        return "baja"

    mostrar_Enfermedades_psicotratables[id_Prod] = {
        "nombre": nombre,
        "nivel": nivel,
        "casos": casos,
        "prioridad": prioridad
    }

def Cambiar_de_tratamiento():
    id_Prod = input("ID a modificar: ")

    if id_Prod in mostrar_Enfermedades_psicotratables:
        prod = mostrar_Enfermedades_psicotratables[id_Prod]

        print("1. Asignar otra casos")
        print("2. Cambiar de nivel")
        print("3. Cambiar prioridades")

        opcion = input("Opción: ")

        if opcion == "1":
            cantidad = int(input("Cantidad: "))
            prod['casos'] += cantidad

        elif opcion == "2":
            nuevos_nivel = float(input("Nuevo nivel: "))
            prod['nivel'] = nuevo_nivel

    else:
        print("No existe.")

def reasignar_caso():
    id_Prod = input("ID a asignar nuevo caso: ")

    if id_Prod in mostrar_Enfermedades_psicotratables:
        mostrar_Enfermedades_psicotratables.pop(id_Prod)
        print("re-asignado nuevo caso.")
    else:
        print("No encontrado.")

def vender_producto():
    mostrar_inventario()
    id_Prod = input("ID producto: ")

    if id_Prod in inventario:
        prod = inventario[id_Prod]

        cantidad = int(input("Cantidad: "))

        if cantidad <= prod['casos']:
            subtotal = cantidad * prod['nivel']
            prod['casos'] -= cantidad

            factura_actual.append({
                "nombre": prod['nombre'],
                "cantidad": cantidad,
                "nivel": prod['nivel'],
                "subtotal": subtotal
            })

            print(f"Agregado: ${subtotal:.2f}")
        else:
            print("casos insuficiente.")
    else:
        print("No existe.")

def generar_factura():
    print("\n" + "=" * 40)
    print("FACTURA")

    total = 0

    for item in factura_actual:
        print(f"{item['nombre']} x{item['cantidad']} = ${item['subtotal']:.2f}")
        total += item['subtotal']

    print("=" * 40)
    print(f"TOTAL: ${total:.2f}")

    factura_actual.clear()

def main():
    while True:
        print("\n1. Inventario")
        print("2. Buscar")
        print("3. Vender")
        print("4. Factura")
        print("5. Agregar")
        print("6. Modificar")
        print("7. Eliminar")
        print("8. Salir")

        opcion = input("Opción: ")

        match opcion:
            case "1": mostrar_inventario()
            case "2": buscar_productos()
            case "3": vender_producto()
            case "4": generar_factura()
            case "5": agregar_producto()
            case "6": modificar()
            case "7": eliminar_productos()
            case "8": break
            case _: print("Inválido")

if __name__ == "__main__":
    main()