# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17Rde_GQPQjGdC-xQCR2cmroDfJrRerOn
"""

class Vehiculo:

  def mover(self):
    print("El vehiculo se esta moviendo")
    class Moto(Vehiculo):
        pass

    def main():

      vehiculo1 = Vehiculo ()
      moto1 = Moto()
      print("Metodo desde de la clase vehiculo")
      moto1.Mover()

      if __name__ == "__main__":
        main()

class Empleado:
  def trabajar(self):
    print("El empleado esta generando tareas generales")

    class Gerente(Empleado):
      def trabajar(self):
        print("El Gerente esta revisando informes")
      pass

    class Vendedor(Empleado):
      def trabajar(self):
          print("El vendedor esta atendiendo clientes")
      pass

      Frutas = ["manzana", "banana", "cereza"]
      for Frutas in frutas:
        print(Frutas)

      for i in rango(5):
        print(f"Iteración {i}")

  def main():
      gerente1 = Gerente()
      gerente1.trabajar()
      vendedor1 = Vendedor()
      vendedor1.trabajar()

  if __name__ == 'main':
      main()

class Animal:
  def sonidos(self):
    print("El empleado esta generando tareas generales")

    class Gallo(Animal):
      def especie(self):
        print("El gallo canto")
      pass

    class leon(Animal):
      def especie(self):
          print("El leon hace unrugido")
      pass

    class perro(Animal):
      def especie(self):
          print("El perro ladra")
      pass

    class Aguila(Animal):
      def especie(self):
          print("El aguíla dice Pajaro")
      pass

      Comidas = ["manzana", "banana", "huesos", "carne", "cemillas"]
      for Comidas in Comidas:
        print(Comidas)

      for i in rango(5):
        print(f"Iteración {i}")

  def main():
      perro1 = perro1()
      perro1.especie()
      leon1 = leon1()
      leon1.Especie()
      gallo1 = gallo1()
      gallo1.Gallo()
      aguila1 = aguila1()
      aguila1.Aguila()




  if __name__ == 'main':
      main()

class Vehiculo:
    def manejo(self):
      print("el vehiculo se maneja de cierta forma: ")

    class moto(Vehiculo):
      def movilidad(self):
        print("La moto ayuda movilizar de manera más rapida: ")
      pass
    class patines(Vehiculo):
      def movilidad(self):
          print("La son comodos: ")
      pass
    class globo(Vehiculo):
      def movilidad(self):
          print("La globo ayuda a ver los horizontes: ")
      pass
    class bicicleta(Vehiculo):
      def movilidad(self):
          print("La bicicleta ayuda movilizar de manera más comoda: ")
      pass

      combustible = ["Gasolina", "Fuerza", "fuego", "madera"]
      for combustible in combustible:
        print(combustible)

      for i in rango(5):
        print(f"Iteración {i}")

    def main():
      moto1 = moto1()
      moto1.movilidad()
      patines1 = patines1()
      patines1.movilidad()
      globo1 = globo1()
      globo1.movilidad()
      bicicleta1 = bicicleta1()
      bicicleta1.movilidad()




    if __name__ == 'main':
      main()

class Maquina:
    def movilidad(self):
      print("el vehiculo se maneja de cierta forma: ")

    class moto(Recorrido):
      def movilidad(self):
        print("La moto ayuda movilizar de manera más rapida: ")
      pass
    class patines(Recorrido):
      def movilidad(self):
          print("La son comodos: ")
      pass
    class globo(Recorrido):
      def movilidad(self):
          print("La globo ayuda a ver los horizontes: ")
      pass
    class bicicleta(Recorrido):
      def movilidad(self):
          print("La bicicleta ayuda movilizar de manera más comoda: ")
      pass

      combustible = ["Gasolina", "Fuerza", "fuego", "madera"]
      for combustible in combustible:
        print(combustible)

      for i in range(5):
        print(f"Iteración {i}")

    def main():
      moto1 = moto1()
      moto1.movilidad()
      patines1 = patines1()
      patines1.movilidad()
      globo1 = globo1()
      globo1.movilidad()
      bicicleta1 = bicicleta1()
      bicicleta1.movilidad()




    if __name__ == 'main':
      main()

class padre:
  def __init__(self, mensaje):
    self .mensaje = mensaje

class Hijo(padre):
  def __init__(self, mensaje, nombre) -> True:
     super().__init__(mensaje) #
     self.nombre = nombre

def main():
    objePadre = padre("padre")
    print(objePadre.mensaje)
    print(objeHijo.mensaje)
    print(objeHijo.mensaje)
    objeHijo = Hijo("hijo", "josecito perezati")

for i in range(11):
    for j in range(i):
        print (i, end=' ')
    print()



    if __name__ == 'main':
      main()

class Operacion:
    def __init__(self, dato1, dato2):
        self.dato1 = dato1
        self.dato2 = dato2

    def calcular(self):
        pass


class Suma(Operacion):
    def calcular(self):
        resultado = self.dato1 + self.dato2
        print(f"La suma es: {resultado}")


class Resta(Operacion):
    def calcular(self):
        resultado = self.dato1 - self.dato2
        print(f"La resta es: {resultado}")


class Multiplicacion(Operacion):
    def calcular(self):
        resultado = self.dato1 * self.dato2
        print(f"La multiplicación es: {resultado}")


class Division(Operacion):
    def calcular(self):
        if self.dato2 != 0:
            resultado = self.dato1 / self.dato2
            print(f"La división es: {resultado}")
        else:
            print("No se puede dividir entre cero")


def main():
    dato1 = float(input("Ingrese el primer número: "))
    dato2 = float(input("Ingrese el segundo número: "))

    operacion1 = Suma(dato1, dato2)
    operacion1.calcular()

    operacion2 = Resta(dato1, dato2)
    operacion2.calcular()

    operacion3 = Multiplicacion(dato1, dato2)
    operacion3.calcular()

    operacion4 = Division(dato1, dato2)
    operacion4.calcular()




if __name__ == "__main__":
    main()

class Operaciones:
    def __init__(self, a, b):
        self.a = a
        self.b = b
        print("Inicializamos operaciones")

    def calcular(self):
        print("Operación genérica")


class Suma(Operaciones):
    def calcular(self):
        resultado = self.a + self.b
        print(f"La suma es: {resultado}")
        return resultado


class Resta(Operaciones):
    def calcular(self):
        resultado = self.a - self.b
        print(f"La resta es: {resultado}")
        return resultado


class Division(Operaciones):
    def calcular(self):
        if self.b == 0:
            print("Error: No se puede dividir entre cero")
            return None
        resultado = self.a / self.b
        print(f"La división es: {resultado}")
        return resultado


class Potencia(Operaciones):
    def calcular(self):
        resultado = self.a ** self.b  # ** es potencia en Python
        print(f"La potencia es: {resultado}")
        return resultado


def main():
    num1 = float(input("Ingrese el primer número: "))
    num2 = float(input("Ingrese el segundo número: "))

    print("---------------------")
    Suma(num1, num2).calcular()

    print("---------------------")
    Resta(num1, num2).calcular()

    print("---------------------")
    Division(num1, num2).calcular()

    print("---------------------")
    Potencia(num1, num2).calcular()


if __name__ == '__main__':
    main()