# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15lezBcCgi54roJvNLSV1ZqOd-WoBOeCG
"""

class Alumno:
    def __init__(self, estudiante, edad, promedio, grado, id):
        self.estudiante = estudiante
        self.edad = edad
        self.promedio = promedio
        self.grado = grado
        self.id = id

    def get_estudiante(self):
        return self.estudiante

    def set_estudiante(self, nuevo_estudiante):
        if isinstance(nuevo_estudiante, str):
            self.estudiante = nuevo_estudiante
        else:
            print("Ingrese nombre del estudiante válido")

    def set_grado(self, nuevo_grado):
        if isinstance(nuevo_grado, str):
            self.grado = nuevo_grado
        elif isinstance(nuevo_grado, int) and nuevo_grado > 0:
            self.grado = nuevo_grado
        else:
            print("Ingrese un grado válido")

    def get_estudiante(self):
        return self.grado

    def set_id(self, nuevo_id):
        if isinstance(nuevo_id, int) and nuevo_id >= 0:
            self.id = nuevo_id
        else:
            print("Ingrese un identificador válido")

    def get_estudiante(self):
        return self.estudiante

    def set_promedio(self, nuevo_promedio):
        if isinstance(nuevo_promedio, (int, float)):
            self.promedio = nuevo_promedio
        else:
            print("Ingrese un promedio válido")

    def set_edad(self, nueva_edad):
        if isinstance(nueva_edad, int):
            self.edad = nueva_edad
        else:
            print("Ingrese una edad válida")

    def mostrar_info(self):
        print("Estudiante:", self.estudiante)
        print("Grado:", self.grado)
        print("ID:", self.id)
        print("Promedio:", self.promedio)
        print("Edad:", self.edad)


def main():
    print("\n=== SISTEMA PARA REGISTRO DE ALUMNOS ===")
    alumno1 = Alumno("Alexander Pinzón", 18, 3.7, "decimo", 1)
    print("-----------------------")
    alumno2 = Alumno("Marcos Alvares", 16, 3.8, "octabo", 2)
    alumno2.mostrar_info()
    print("----------------------")
    alumno3 = Alumno("Marcos Alvares", 15, 3.4, "octabo", 3)
    alumno3.mostrar_info()
    print("----------------------")
    alumno4 = Alumno("Marcos Alvares", 15, 4.0, "octabo", 4)
    alumno1.mostrar_info()

    print("----------------------")
    alumno4 = Alumno("Marcos Alvares", 15, 4.0, "octabo", 4)
    alumno1.mostrar_info()

if __name__ == "__main__":
    main()

class Mueble:
    def __init__(self, id, nombre, descripcion, dimensiones, color, propiedad, material, ubicacion):
        self.id = id
        self.nombre = nombre
        self.descripcion = descripcion
        self.dimensiones = dimensiones
        self.color = color
        self.propiedad = propiedad
        self.material = material
        self.ubicacion = ubicacion

    def mostrar_datos(self):
        print("Identificador:", self.id)
        print("Nombre:", self.nombre)
        print("Descripción:", self.descripcion)
        print("Dimensiones:", self.dimensiones)
        print("Color:", self.color)
        print("Propiedad:", self.propiedad)
        print("Material:", self.material)
        print("Ubicación:", self.ubicacion)


def main():
    print("\n=== SISTEMA PARA REGISTRO DE MUEBLES TIENDA ===")

    muebles1 = Mueble(
        1,
        "HAMMARN",
        "Sofá cama, Knisa gris oscuro/negro",
        "120x85x78 cm",
        "Gris oscuro",
        "Interior",
        "Metal y tela",
        "Sala de exhibición A"
    )

    muebles2 = Mueble(
        2,
        "GLOSTAD",
        "Sofá 2 puestos, Knisa gris oscuro",
        "140x78x75 cm",
        "Gris",
        "Interior",
        "Madera y tela",
        "Sala de exhibición B"
    )

    muebles3 = Mueble(
        3,
        "LACK",
        "Mesa de centro rectangular",
        "90x55x45 cm",
        "Blanco",
        "Interior",
        "Madera aglomerada",
        "Sección mesas"
    )

    muebles4 = Mueble(
        4,
        "MALM",
        "Cama doble con cajones",
        "200x160x100 cm",
        "Negro",
        "Interior",
        "Madera",
        "Sección dormitorios"
    )

    muebles5 = Mueble(
        5,
        "HEMNES",
        "Cómoda 8 cajones",
        "160x50x96 cm",
        "Blanco",
        "Interior",
        "Madera maciza",
        "Sección almacenamiento"
    )

    print("----------------------")
    muebles1.mostrar_datos()
    print("----------------------")
    muebles2.mostrar_datos()
    print("----------------------")
    muebles3.mostrar_datos()
    print("----------------------")
    muebles4.mostrar_datos()
    print("----------------------")
    muebles5.mostrar_datos()


if __name__ == "__main__":
    main()